languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
baseurl = "/"
googleAnalytics = ""
theme = "hugo-vitae"

[params]
  author = "Chris Halder"
  title = "Chris Halder's Resume"
  description = "Chris Halder's Resume"
  avatar = "0.jpeg"
  email = "mail Chris / "
  email_full = "mailto:chrishr2000@gmail.com?subject=Got your resume"
  website = "LinkedIn"
  website_full = "http://www.linkedin.com/in/chrishalder"
  #github = "dwaiba"
  #twitter = "cloudgeario"
  linkedin = "chrishalder"
  #tel = "+44 0000 000000"
  #tel_full = "+440000000000"
  google_maps = "https://www.google.com/maps/place/Woudlaan+Zoetermeer"
  #address = "44 Perth Street"
  #postcode = "EH3 5BL"
  city = "Zoetermeer"
  country = "The Netherlands"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
