languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
baseurl = "/"
googleAnalytics = ""
theme = "hugo-vitae"

[params]
  author = "Chris Halder"
  title = "Chris Halder's Resume"
  description = "Chris Halder's Resume"
  avatar = "1521424_10152957250893785_1358865765019084501_n.jpg"
  email = "mail Chris / "
  email_full = "mailto:chrishr2000@gmail.com?subject=Got your resume"
  linkedin = "chrishalder"
  google_maps = "https://www.google.com/maps/place/Woudlaan+Zoetermeer"
  city = "Zoetermeer"
  country = "The Netherlands"
  website = "Download the resume pdf"
  website_full = "http://chris.cloudgear.io/img/chris.pdf"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
